#ifndef _ERROR_CONSTANTS_H

#define _ERROR_CONSTANTS_H

#define ERROR_OPEN_FILE -1
#define ERROR_COUNT_POINTS -2
#define ERROR_INPUT_POINTS -3
#define ERROR_COUNT_CONNECTIONS -4
#define ERROR_INPUT_CONNECTIONS -5
#define ERROR_FILL -1
#define ERROR_CHECK -7
#endif
