#ifndef _ERROR_CONSTANTS_H

#define _ERROR_CONSTANTS_H

#define ERROR_NUMBER 1
#define ERROR_OPEN_FILE -1
#define ERROR_COUNT_POINTS -2
#define ERROR_INPUT_POINTS -3
#define ERROR_COUNT_CONNECTIONS -4
#define ERROR_INPUT_CONNECTIONS -5
#define ERROR_FILL -6
#define ERROR_CHECK -7
#define ERROR_EMPTY_INPUT -8
#define ERROR_INPUT_SYMBOL -9
#define ERROR_COMMAND -10
#define ERROR_ALLOCATION_MEMORY -11
#define ERROR_FILL_CONNECTIONS -12
#define ERROR_FILL_POINTS -13
#define READ_ERROR -15
#define ERROR_COUNT -14

#endif
